In [1]:
#不同的形态学操作，例如侵蚀，膨胀，开运算，闭运算

#cv.erode(),cv.dilate(), cv.morphologyEx()

In [1]:
import cv2 as cv
import numpy as np

img = cv.imread('j.png',0)

#侵蚀
kernel = np.ones((5,5),np.uint8)
erosion = cv.erode(img,kernel,iterations = 1)

#扩张
dilation = cv.dilate(img,kernel,iterations = 1) 

#开运算
opening = cv.morphologyEx(img, cv.MORPH_OPEN, kernel) 

#闭运算
closing = cv.morphologyEx(img, cv.MORPH_CLOSE, kernel) 

#形态学梯度
gradient = cv.morphologyEx(img, cv.MORPH_GRADIENT, kernel) 

#顶帽
tophat = cv.morphologyEx(img, cv.MORPH_TOPHAT, kernel) 

#黑帽
blackhat = cv.morphologyEx(img, cv.MORPH_BLACKHAT, kernel)



In [2]:
#OpenCV具有一个函数cv.getStructuringElement()。
#您只需传递内核的形状和大小，即可获得所需的内核。
# 矩形内核
cv.getStructuringElement(cv.MORPH_RECT,(5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [3]:
# 椭圆内核
cv.getStructuringElement(cv.MORPH_ELLIPSE,(5,5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [4]:
# 十字内核
cv.getStructuringElement(cv.MORPH_CROSS,(5,5))

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)